---
core:
    num_workers: 100


inventory:
    plugin: nornir.plugins.inventory.simple.SimpleInventory
    options:
        host_file: "/home/ipvzero/ISIS/hosts.yaml"
        group_file: "/home/ipvzero/ISIS/groups.yaml"
        defaults_file: "/home/ipvzero/ISIS/defaults.yaml"
